name: Kaggle Badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: "17 11 * * *"
  workflow_dispatch:

jobs:
  create-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Puppeteer with specific Chrome version
        env:
          PUPPETEER_CACHE_DIR: /home/runner/.cache/puppeteer
          PUPPETEER_CHROMIUM_REVISION: 1290666  # Especifica a versão do Chrome
        run: |
          mkdir -p $PUPPETEER_CACHE_DIR
          npx puppeteer browsers install chrome

      - name: Use Kaggle Badges Action
        env:
          PUPPETEER_CACHE_DIR: /home/runner/.cache/puppeteer
        uses: spider-man-tm/kaggle-badges@v1.2.6
        with:
          user_name: brunoraiado

      - name: Commit and Push SVG files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./kaggle-badges/* ./kaggle-plates/*
          git commit -m "Add generated SVG files" || echo "No changes to commit"
          git push
