name: Kaggle Badges
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  create-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev

      - name: Install Puppeteer and Chrome
        run: |
          npm init -y
          npm install puppeteer
          npm install puppeteer-core
          npm install @puppeteer/browsers

      - name: Setup Chrome
        run: |
          npx puppeteer browsers install chrome@stable
          npx puppeteer browsers install chrome-headless-shell@stable

      - name: Add wait time
        run: sleep 30

      - name: Use Kaggle Badges Action
        uses: spider-man-tm/kaggle-badges@v1.0.0
        with:
          user_name: brunoraiado
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Kaggle badges"
          git push
